### ISSUE TITLE
This original code has a unintentialal but very serious mistake

### ISSUE THREAD

**Issue by NeuSpeech** [MikeWangWZHL/EEG-To-Text#5]
more details at https://github.com/NeuSpeech/EEG-To-Text

**Comment by MikeWangWZHL** [comment]
Thank you very much for pointing this out, this is indeed an unintentional but critical bug, we have updated the codebased and put up a note linking to your correction; thanks again for your great contribution!

**Comment by NeuSpeech** [comment]
I strongly suggest that you re-run your experiments with new codebase and report new performance in your paper, and post it in this repo. Your previous high performance has misleaded many people already.
