### ISSUE TITLE
ERROR in README?

### ISSUE THREAD

**Issue by fedezuc** [MikeWangWZHL/EEG-To-Text#9]
There is commit dated Jan 19th 2024 but in the README the update date is 19th Jan 2023. Is it a typo?

**Comment by fedezuc** [comment]
> There is commit dated Jan 19th 2024 but in the README the update date is 19th Jan 2023. Is it a typo?

**Comment by MikeWangWZHL** [comment]
yes this is a typo, thank you for the catch!
